#include "../../public/Objects/RdrHorse.h"
#include "..\..\public\Math\MathUtils.h"

namespace game
{
    std::vector<std::string> RdrHorse::models = {
        "A_C_Horse_AmericanPaint_Greyovero",
        "A_C_Horse_AmericanPaint_Overo",
        "A_C_Horse_AmericanPaint_SplashedWhite",
        "A_C_Horse_AmericanPaint_Tobiano",
        "A_C_Horse_AmericanStandardbred_Black",
        "A_C_Horse_AmericanStandardbred_Buckskin",
        "A_C_Horse_AmericanStandardbred_Lightbuckskin",
        "A_C_Horse_AmericanStandardbred_PalominoDapple",
        "A_C_Horse_AmericanStandardbred_SilverTailBuckskin",
        "A_C_Horse_Andalusian_DarkBay",
        "A_C_Horse_Andalusian_Perlino",
        "A_C_Horse_Andalusian_Perlino",
        "A_C_Horse_Andalusian_RoseGray",
        "A_C_Horse_Appaloosa_BlackSnowflake",
        "A_C_Horse_Appaloosa_Blanket",
        "A_C_Horse_Appaloosa_BrownLeopard",
        "A_C_Horse_Appaloosa_FewSpotted_PC",
        "A_C_Horse_Appaloosa_Leopard",
        "A_C_Horse_Appaloosa_LeopardBlanket",
        "A_C_Horse_Arabian_Black",
        "A_C_Horse_Arabian_Grey",
        "A_C_Horse_Arabian_RedChestnut",
        "A_C_Horse_Arabian_RedChestnut_PC",
        "A_C_Horse_Arabian_RoseGreyBay",
        "A_C_Horse_Arabian_WarpedBrindle_PC",
        "A_C_Horse_Arabian_White",
        "A_C_Horse_Ardennes_BayRoan",
        "A_C_Horse_Ardennes_IronGreyRoan",
        "A_C_Horse_Ardennes_StrawberryRoan",
        "A_C_Horse_Belgian_BlondChestnut",
        "A_C_Horse_Belgian_MealyChestnut",
        "A_C_Horse_Breton_GrulloDun",
        "A_C_Horse_Breton_MealyDappleBay",
        "A_C_Horse_Breton_RedRoan",
        "A_C_Horse_Breton_Sealbrown",
        "A_C_Horse_Breton_Sorrel",
        "A_C_Horse_Breton_SteelGrey",
        "A_C_Horse_Buell_WarVets",
        "A_C_Horse_Criollo_Baybrindle",
        "A_C_Horse_Criollo_Bayframeovero",
        "A_C_Horse_Criollo_Blueroanovero",
        "A_C_Horse_Criollo_Dun",
        "A_C_Horse_Criollo_Marblesabino",
        "A_C_Horse_Criollo_Sorrelovero",
        "A_C_Horse_DutchWarmblood_ChocolateRoan",
        "A_C_Horse_DutchWarmblood_SealBrown",
        "A_C_Horse_DutchWarmblood_SootyBuckskin",
        "A_C_Horse_EagleFlies",
        "A_C_Horse_Gang_arthur",
        "A_C_Horse_Gang_Bill",
        "A_C_Horse_Gang_Charles",
        "A_C_Horse_Gang_Charles_EndlessSummer",
        "A_C_Horse_Gang_Hosea",
        "A_C_Horse_Gang_Javier",
        "A_C_Horse_Gang_John",
        "A_C_Horse_Gang_Karen",
        "A_C_Horse_Gang_Kieran",
        "A_C_Horse_Gang_Sadie",
        "A_C_Horse_Gang_Sean",
        "A_C_Horse_Gang_Trelawney",
        "A_C_Horse_Gang_Uncle",
        "A_C_Horse_Gang_Uncle_EndlessSummer",
        "A_C_Horse_GypsyCob_PalominoBlagdon",
        "A_C_Horse_GypsyCob_Piebald",
        "A_C_Horse_GypsyCob_Skewbald",
        "A_C_Horse_GypsyCob_SplashedBay",
        "A_C_Horse_GypsyCob_SplashedPiebald",
        "A_C_Horse_GypsyCob_WhiteBlagdon",
        "A_C_Horse_HungarianHalfbred_DarkDappleGrey",
        "A_C_Horse_HungarianHalfbred_FlaxenChestnut",
        "A_C_Horse_HungarianHalfbred_LiverChestnut",
        "A_C_Horse_HungarianHalfbred_PiebaldTobiano",
        "A_C_Horse_John_EndlessSummer",
        "A_C_Horse_KentuckySaddle_Black",
        "A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC",
        "A_C_Horse_KentuckySaddle_ChestnutPinto",
        "A_C_Horse_KentuckySaddle_Grey",
        "A_C_Horse_KentuckySaddle_SilverBay",
        "A_C_Horse_Kladruber_Black",
        "A_C_Horse_Kladruber_Cremello",
        "A_C_Horse_Kladruber_Dapplerosegrey",
        "A_C_Horse_Kladruber_Grey",
        "A_C_Horse_Kladruber_Silver",
        "A_C_Horse_Kladruber_White",
        "A_C_Horse_MissouriFoxTrotter_AmberChampagne",
        "A_C_Horse_MissouriFoxTrotter_Blacktovero",
        "A_C_HORSE_MISSOURIFOXTROTTER_BLUEROAN",
        "A_C_Horse_MissouriFoxTrotter_Buckskinbrindle",
        "A_C_HORSE_MISSOURIFOXTROTTER_DAPPLEGREY",
        "A_C_Horse_MissouriFoxTrotter_SableChampagne",
        "A_C_Horse_MissouriFoxTrotter_SilverDapplePinto",
        "A_C_Horse_Morgan_Bay",
        "A_C_Horse_Morgan_BayRoan",
        "A_C_Horse_Morgan_FlaxenChestnut",
        "A_C_Horse_Morgan_LiverChestnut_PC",
        "A_C_Horse_Morgan_Palomino",
        "A_C_Horse_MP_Mangy_Backup",
        "A_C_Horse_MurfreeBrood_Mange_01",
        "A_C_Horse_MurfreeBrood_Mange_02",
        "A_C_Horse_MurfreeBrood_Mange_03",
        "A_C_HORSE_MUSTANG_BLACKOVERO",
        "A_C_HORSE_MUSTANG_BUCKSKIN",
        "A_C_HORSE_MUSTANG_CHESTNUTTOVERO",
        "A_C_Horse_Mustang_GoldenDun",
        "A_C_Horse_Mustang_GrulloDun",
        "A_C_HORSE_MUSTANG_REDDUNOVERO",
        "A_C_Horse_Mustang_TigerStripedBay",
        "A_C_Horse_Mustang_WildBay",
        "A_C_Horse_Nokota_BlueRoan",
        "A_C_Horse_Nokota_ReverseDappleRoan",
        "A_C_Horse_Nokota_WhiteRoan",
        "A_C_Horse_NorfolkRoadster_Black",
        "A_C_Horse_NorfolkRoadster_DappledBuckskin",
        "A_C_Horse_NorfolkRoadster_PiebaldRoan",
        "A_C_Horse_NorfolkRoadster_RoseGrey",
        "A_C_Horse_NorfolkRoadster_SpeckledGrey",
        "A_C_Horse_NorfolkRoadster_SpottedTricolor",
        "A_C_Horse_Shire_DarkBay",
        "A_C_Horse_Shire_LightGrey",
        "A_C_Horse_Shire_RavenBlack",
        "A_C_Horse_SuffolkPunch_RedChestnut",
        "A_C_Horse_SuffolkPunch_Sorrel",
        "A_C_Horse_TennesseeWalker_BlackRabicano",
        "A_C_Horse_TennesseeWalker_Chestnut",
        "A_C_Horse_TennesseeWalker_DappleBay",
        "A_C_Horse_TennesseeWalker_FlaxenRoan",
        "A_C_Horse_TennesseeWalker_GoldPalomino_PC",
        "A_C_Horse_TennesseeWalker_MahoganyBay",
        "A_C_Horse_TennesseeWalker_RedRoan",
        "A_C_Horse_Thoroughbred_BlackChestnut",
        "A_C_Horse_Thoroughbred_BloodBay",
        "A_C_Horse_Thoroughbred_Brindle",
        "A_C_Horse_Thoroughbred_DappleGrey",
        "A_C_Horse_Thoroughbred_ReverseDappleBlack",
        "A_C_HORSE_TURKOMAN_BLACK",
        "A_C_HORSE_TURKOMAN_CHESTNUT",
        "A_C_Horse_Turkoman_DarkBay",
        "A_C_Horse_Turkoman_Gold",
        "A_C_HORSE_TURKOMAN_GREY",
        "A_C_HORSE_TURKOMAN_PERLINO",
        "A_C_Horse_Turkoman_Silver",
        "A_C_Horse_Winter02_01",
        // "A_C_HorseMule_01",
        // "A_C_HorseMulePainted_01"
    };

    RdrHorse::RdrHorse(std::string model, Vector3 position): model_(std::move(model))
    {
        RdrLogger* logger = RdrLogger::get_logger("GangRescue.log", LogLevel::INFO);
        stringstream debug;

        debug << "Model requested is " << this->model_;
        logger->info(debug.str().c_str());
        debug.str("");
            
        ped_ = std::shared_ptr<game::RdrPed>(game::RdrPed::create_ped(this->model_.c_str(), position, 0));
            
        debug << "Created horse ped with id " << ped_ << " and model " << this->model_.c_str();
        logger->info(debug.str().c_str());
            
    }

    std::string RdrHorse::get_random_horse_model()
    {
        const int model_index = random_number_in_range(0, static_cast<int>(models.size()) - 1);
        return models[model_index];
    }
}
